services:
  db:
    image: postgres:17
    container_name: scannerx-postgres
    environment:
      POSTGRES_DB: scannerx
      POSTGRES_USER: scannerx
      POSTGRES_PASSWORD: scannerx
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scannerx -d scannerx"]
      interval: 10s
      timeout: 5s
      retries: 5

  mq:
    image: rabbitmq:3-management
    container_name: scannerx-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rmq-data:/var/lib/rabbitmq

  cache:
    image: redis:7
    container_name: scannerx-redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  rmq-data:
