ALTER TABLE scans
    ADD COLUMN pause_requested BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN current_stage_order INT NULL,
    ADD COLUMN resume_stage_order INT NULL,
    ADD COLUMN paused_at TIMESTAMP NULL;

CREATE TABLE scan_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id BIGINT NOT NULL,
    type VARCHAR(64) NOT NULL,
    stage_order INT NULL,
    message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scan_activity_scan FOREIGN KEY (scan_id) REFERENCES scans(id) ON DELETE CASCADE
);
